# Generated by Django 4.1 on 2022-08-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_team_member1_team_member2_team_member3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Challenge name', max_length=100)),
                ('priority', models.PositiveIntegerField(help_text='Challenge priority')),
                ('validator', models.CharField(help_text='Name of the validator function', max_length=100)),
                ('description', models.TextField(help_text='Challenge description')),
            ],
        ),
    ]
