# Generated by Django 4.1 on 2022-08-18 10:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_challenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField(blank=True, default=datetime.datetime.now)),
                ('done_at', models.DateField(null=True)),
                ('status', models.CharField(blank=True, choices=[('s', 'Started'), ('c', 'Completed')], default='s', help_text='Challenge status', max_length=1)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='server.challenge')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='server.team')),
            ],
        ),
    ]
