# Generated by Django 4.1 on 2022-08-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_challengeinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeinstance',
            name='done_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
