# Generated by Django 4.1 on 2022-08-18 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_challengeinstance_done_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeinstance',
            name='done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challengeinstance',
            name='started_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
