# Generated by Django 4.1 on 2022-08-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_alter_challengeinstance_done_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='minimal_version',
            field=models.CharField(default='0.0.1', help_text='Minimal API version required', max_length=12),
            preserve_default=False,
        ),
    ]
