# Generated by Django 4.1 on 2022-08-19 13:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_first_challenge_and_first_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('correct', models.BooleanField()),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='server.challenge')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='server.team')),
            ],
        ),
    ]
