# Generated by Django 4.1 on 2022-08-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_challengeattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeattempt',
            name='details',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='base_url',
            field=models.CharField(default='', help_text='Base URL to check API against', max_length=100),
            preserve_default=False,
        ),
    ]
