# Generated by Django 4.1 on 2022-08-21 19:15

from django.db import migrations

def challenge_2(apps, schema_editor):
    Challenge = apps.get_model('server', 'Challenge')
    chall = Challenge(
        name='My name is Bond, API Bond',
        priority=2,
        minimal_version="0.0.2",
        validator="check_api_secret",
        description="""# Well played!
Your API is now alive and you reach the first step of many more to come!
As seen during the course, managing secrets is an important part.
Your API will have to use one on a specific endpoint.

On Vault, a secret has been setup for you.
This secret is the token your API will use later.
To access it, create a template for environmental variable in your Nomad file.
Create an environmental variable named `API_SECRET`.
In your template, use the secret from `gis_kv/team_XX/token`.

## Goal
You will create an endpoint named `/identify`.
This endpoint will expose the `sha256` of your API token.
""",
    )
    chall.save()

class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_challengeattempt_details_team_base_url'),
    ]

    operations = [
        migrations.RunPython(challenge_2),
    ]
