# Generated by Django 4.1 on 2022-09-21 18:37

from django.db import migrations

name='Linear Regression'

def challenge(apps, schema_editor):
    Challenge = apps.get_model('server', 'Challenge')
    chall = Challenge(
        name=name,
        priority=21,
        minimal_version="0.0.21",
        validator="algo_linear_reg",
        description="""# Linear regression
The kNN regression is done, well played!

Using the same payload as before, use the `LogisticRegression`.

The endpoint to create is `/algo/linear/regressor`.

## Goal

You will have to return the predicted value and its precision.
```
{
  "predicted_value": 0.2,
  "precision": 0.8
}
```
""",
    )
    chall.save()

def reverse_challenge(apps, schema_editor):
    Challenge = apps.get_model('server', 'Challenge')
    challs = Challenge.objects.filter(name=name)
    for chall in challs:
        chall.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('server', '0020_challenge_prio_20'),
    ]

    operations = [
        migrations.RunPython(challenge, reverse_challenge)
    ]
