# Generated by Django 4.1 on 2022-09-21 18:37

from django.db import migrations

name='Neural network regression'

def challenge(apps, schema_editor):
    Challenge = apps.get_model('server', 'Challenge')
    chall = Challenge(
        name=name,
        priority=23,
        minimal_version="0.0.23",
        validator="algo_mlp_reg",
        description="""# Multi Layer Perceptron regressor
Well played with the decision tree!

Let's do some neural network for the last algorithm of the introduction part.
We will use the `MLPRegressor` with the random state being your team number.
Using the same payload as before, but, implement the endpoint `/algo/mlp/reg`.

## Goal

You will have to return the predicted value and classifier training score.
```
{
  "predicted_value": 0.2,
  "score": 0.8
}
```
""",
    )
    chall.save()

def reverse_challenge(apps, schema_editor):
    Challenge = apps.get_model('server', 'Challenge')
    challs = Challenge.objects.filter(name=name)
    for chall in challs:
        chall.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('server', '0022_challenge_prio_22'),
    ]

    operations = [
        migrations.RunPython(challenge, reverse_challenge)
    ]
